<?php
session_start();
require __DIR__.'/db.php';
require __DIR__.'/config.php';
$expected=(string)($ADMIN_TOKEN??'');
if(isset($_POST['token'])){if($expected!==''&&hash_equals($expected,(string)$_POST['token']))$_SESSION['bird_admin']=true;else $error='Invalid admin token.';}
if(isset($_POST['logout'])){unset($_SESSION['bird_admin']);header('Location: admin.php');exit;}
$admin=!empty($_SESSION['bird_admin']);
if(!$admin): ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bird ID Admin Login</title><style>body{font-family:system-ui;background:#f4f7f5;padding:30px}.card{max-width:420px;margin:auto;background:#fff;padding:24px;border-radius:18px;box-shadow:0 10px 35px #0001}input,button{width:100%;padding:12px;margin-top:10px;border-radius:10px;border:1px solid #ccd8d0;box-sizing:border-box}button{font-weight:700;cursor:pointer}</style></head><body><div class="card"><h1>🛠️ Bird ID Admin</h1><p>Enter the server-side admin token.</p><?php if(isset($error)): ?><p><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php endif; ?><form method="post"><input type="password" name="token" autocomplete="current-password" required><button>Sign in</button></form></div></body></html><?php exit;endif;
$stats=[];
$stats['users']=(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();
$stats['scans']=(int)$pdo->query('SELECT COUNT(*) FROM scan_logs')->fetchColumn();
$stats['paid']=(int)$pdo->query("SELECT COUNT(*) FROM payments WHERE status='paid'")->fetchColumn();
$stats['revenue']=(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='paid'")->fetchColumn();
$recent=$pdo->query('SELECT id,user_id,provider,amount,scans,status,created_at,paid_at FROM payments ORDER BY id DESC LIMIT 20')->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Bird ID Admin Dashboard</title><style>body{font-family:system-ui;margin:0;background:#f4f7f5;color:#16321f}.wrap{max-width:1100px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.card{background:#fff;padding:20px;border-radius:18px;box-shadow:0 10px 35px #0001}.stat{font-size:30px;font-weight:800}table{width:100%;border-collapse:collapse}th,td{padding:10px;text-align:left;border-bottom:1px solid #e3ebe5}button{padding:9px 14px;border-radius:10px;border:1px solid #ccd8d0;font-weight:700}</style></head><body><main class="wrap"><form method="post" style="float:right"><button name="logout" value="1">Log out</button></form><h1>🛠️ Bird ID Admin Dashboard</h1><div class="grid"><div class="card"><div class="stat"><?=$stats['users']?></div><div>Users / guest identities</div></div><div class="card"><div class="stat"><?=$stats['scans']?></div><div>Successful scans</div></div><div class="card"><div class="stat"><?=$stats['paid']?></div><div>Paid orders</div></div><div class="card"><div class="stat">৳<?=number_format($stats['revenue'],2)?></div><div>Paid revenue</div></div></div><section class="card" style="margin-top:14px"><h2>Recent payments</h2><div style="overflow:auto"><table><tr><th>ID</th><th>Provider</th><th>Amount</th><th>Scans</th><th>Status</th><th>Created</th></tr><?php foreach($recent as $r): ?><tr><td><?=htmlspecialchars($r['id'])?></td><td><?=htmlspecialchars($r['provider'])?></td><td>৳<?=htmlspecialchars($r['amount'])?></td><td><?=htmlspecialchars($r['scans'])?></td><td><?=htmlspecialchars($r['status'])?></td><td><?=htmlspecialchars($r['created_at'])?></td></tr><?php endforeach; ?></table></div></section></main></body></html>
